name: bjndiscover
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter
  google_fonts: ^6.1.0
  hexcolor: ^3.0.1
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  latlong2: ^0.9.0
  flutter_map: ^6.0.1
  mapbox_gl: ^0.16.0
  location: ^5.0.3
  device_info_plus: ^9.1.1
  http: ^1.1.0
  map_launcher: ^2.4.0
  geolocator: ^9.0.2
  flutter_svg: ^0.21.0
  
  
  
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - images/

